# Generated by Django 3.0.2 on 2020-03-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='precio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
