# Generated by Django 3.0.2 on 2020-06-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_inventario_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='flor_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
