# Generated by Django 3.0.2 on 2020-06-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_inventario_flor_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='esta_en_carro',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
