# Generated by Django 3.0.3 on 2020-06-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200614_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='flor_pic',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
